language: node_js
branches:
  only: develop
node_js: '0.10'
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_827ade550aa3_key -iv $encrypted_827ade550aa3_iv
  -in id_rsa.enc -out deployKey -d
- echo -e "Host 42.120.42.45\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- mv deployKey ~\/.ssh/id_rsa
- chmod 600 ~\/.ssh/id_rsa
- git remote add deploy ssh://rot@42.120.42.45:5522/home/cloudenergy/travisDemo.git
- git push deploy
script: npm test
