language: node_js
branches:
  only: develop
node_js: '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_827ade550aa3_key -iv $encrypted_827ade550aa3_iv
  -in travisDemo.enc -out ~\/.ssh/travisDemo -d
- echo -e "Host 42.120.42.45\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: npm test
